<a href="https://colab.research.google.com/github/kousheel05/TASK_AIML-/blob/main/numpy_programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1,)
arr2 = np.array([[5,6,7,9],[1,2,3,4],[5,6,7,8]])
print(arr2)


[1 2 3 4]
[[5 6 7 9]
 [1 2 3 4]
 [5 6 7 8]]


In [8]:
n = np.zeros([2,5])
print(n)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
x = np.ones([4,5])
print(x)
z = np.eye(3)
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
arr = np.arange(2,21,2)
print(arr)
arr3 = np.linspace(1, 10, 5)
print(arr3)

[ 2  4  6  8 10 12 14 16 18 20]
[ 1.    3.25  5.5   7.75 10.  ]


Write a Python program using NumPy to perform the following:

Marks = 65, 78, 90, 55, 88

Tasks:

Create a NumPy array using these marks

Find the average marks

Find the highest marks

Find the lowest marks

In [28]:
p = np.array([65,78,90,55,88])
avg = np.average(p)
hih = np.max(p)
low = np.min(p)
print(avg)
print(hih)
print(low)

75.2
90
55
enter the input


In [ ]:
import numpy as np
p = np.array(list(map(int, input("Enter marks separated by spaces: ").split())))
avg = np.average(p)
hih = np.max(p)
low = np.min(p)
sum = np.sum(p)
sh = np.shape(p)
print("Average:", avg)
print("Highest:", hih)
print("Lowest:", low)
print("sum:",sum)
print("shape:",sh)