<a href="https://colab.research.google.com/github/kousheel05/TASK_AIML-/blob/main/numpy_programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 3. List of Functions and Their Usage

Some important NumPy functions:

| Function | Usage |
|----------|--------|
| `np.array()` | Create an array |
| `np.arange(start, stop, step)` | Create array with range of values |
| `np.zeros((m,n))` | Create array filled with zeros |
| `np.ones((m,n))` | Create array filled with ones |
| `np.eye(n)` | Identity matrix |
| `np.linspace(start, stop, num)` | Create evenly spaced numbers |
| `np.random.rand(m,n)` | Random numbers between 0 and 1 |
| `np.shape` | Get dimensions of array |
| `np.reshape()` | Reshape array |
| `np.sum(), np.mean(), np.std()` | Aggregation functions |
| `np.min(), np.max(), np.argmin(), np.argmax()` | Min/Max values & indices |
| `np.dot(), np.matmul()` | Matrix multiplication |
| `np.transpose()` | Transpose of matrix |
| `np.sort()` | Sorting array |

---

In [6]:
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1,)
arr2 = np.array([[5,6,7,9],[1,2,3,4],[5,6,7,8]])
print(arr2)


[1 2 3 4]
[[5 6 7 9]
 [1 2 3 4]
 [5 6 7 8]]


In [8]:
n = np.zeros([2,5])
print(n)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
x = np.ones([4,5])
print(x)
z = np.eye(3)
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
arr = np.arange(2,21,2)
print(arr)
arr3 = np.linspace(1, 10, 5)
print(arr3)

[ 2  4  6  8 10 12 14 16 18 20]
[ 1.    3.25  5.5   7.75 10.  ]


Write a Python program using NumPy to perform the following:

Marks = 65, 78, 90, 55, 88

Tasks:

Create a NumPy array using these marks

Find the average marks

Find the highest marks

Find the lowest marks

In [28]:
p = np.array([65,78,90,55,88])
avg = np.average(p)
hih = np.max(p)
low = np.min(p)
print(avg)
print(hih)
print(low)

75.2
90
55
enter the input


In [36]:
import numpy as np
p = np.array(list(map(int, input("Enter marks separated by spaces: ").split())))
avg = np.average(p)
hih = np.max(p)
low = np.min(p)
sum = np.sum(p)
sh = np.shape(p)
print("Average:", avg)
print("Highest:", hih)
print("Lowest:", low)
print("sum:",sum)
print("shape:",sh)

Enter marks separated by spaces: 10 20 30 40 50 
Average: 30.0
Highest: 50
Lowest: 10
sum: 150
shape: (5,)


In [35]:
array1 = ([1,2,3,4],[5,6,7,8])
array2 = ([4,6,8,3],[2,5,7,9])
addition = np.sum(array2)
print(addition)

Mean = np.mean(array1)
print(Mean)

standard = np.std(array1)
print(standard)

Min = np.min(array1)
print(Min)
Max = np.max(array1)
print(Max)

ArgMin = np.argmin(array1)
print(ArgMin)

ArgMax = np.argmax(array1)
print(ArgMax)

X = np.array(([3,4],[5,6]))
Y = np.array(([8,9],[6,7]))
Dot = np.dot(X,Y)
print(Dot)

mat = np.arange(2,10).reshape(2,4)
print(mat)
print(mat.T)

sorts = np.sort(array2)
print(sorts)

44
4.5
2.29128784747792
1
8
0
7
[[48 55]
 [76 87]]
[[2 3 4 5]
 [6 7 8 9]]
[[2 6]
 [3 7]
 [4 8]
 [5 9]]
[[3 4 6 8]
 [2 5 7 9]]
